### ISSUE TITLE
Issue with go test

### ISSUE THREAD

**Issue by tuananh1508** [Unee-T-INS/unit#2]
Hi @kaihendry, I got some error when travis run go tes:
go test -v ./... 

Error:
WARN[0000] error getting unee-t env  error=EC2RoleRequestError: no EC2 instance role found
ERROR[0000] failed to retrieve credentials for looking up MYSQL_HOST error=EC2RoleRequestError: no EC2 instance role found

Travis build: https://travis-ci.org/Unee-T-INS/unit

**Comment by kaihendry** [comment]
Tests are not working since the tests assume some categories are setup to insert data. I've disabled them for the time being.

` ERROR[0000] failed to run step1Insert UA= error=Error 1452: Cannot add or update a child row: a foreign key constraint fails (`bugzilla`.`ut_data_to_create_units`, CONSTRAINT `new_unit_unit_creator_bz_id_must_exist` FOREIGN KEY (`bzfe_creator_user_id`) REFERENCES `profiles` (`userid`) ON DELETE NO ACTION ON UPDATE CA) reqid= unit={Talonluck user 55 2 Talonluck Up on the hills and testing}`
